server:
  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  resources:
    limits:
      cpu: 200m
      memory: 2000Mi
    requests:
      cpu: 20m
      memory: 1000Mi
alertmanager:
  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  resources:
    limits:
      cpu: 20m
      memory: 40Mi
    requests:
      cpu: 10m
      memory: 20Mi
kubeStateMetrics:
  resources:
    limits:
      cpu: 20m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 50Mi
nodeExporter:
  resources:
    limits:
      cpu: 20m
      memory: 40Mi
    requests:
      cpu: 10m
      memory: 20Mi
pushgateway:
  resources:
    limits:
      cpu: 25m
      memory: 50Mi
    requests:
      cpu: 15m
      memory: 30Mi
serverFiles:
  alerts:
    groups:
    - name: nodes
      rules:
      - alert: TooManyNodes
        expr: count(kube_node_info) > 3
        for: 15m
        labels:
          severity: notify
        annotations:
          summary: Cluster increased
          description: The number of the nodes in the cluster increased
      - alert: TooFewNodes
        expr: count(kube_node_info) < 1
        for: 15m
        labels:
          severity: notify
        annotations:
          summary: Cluster decreased
          description: The number of the nodes in the cluster decreased
