jenkins:
  controller:
    image: "jenkins/jenkins"
    imageTag: "jdk11"    
    # tag: "2.361.4-jdk11"
    tagLabel: jdk11
    cpu: "500m"
    memory: "2048Mi"
    serviceType: ClusterIP
    serviceAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    installPlugins:
    - configuration-as-code:1569.vb_72405b_80249
    - durable-task:504.vb10d1ae5ba2f
    - workflow-durable-task-step:1234.v019404b_3832a
    - blueocean:1.27.2
    - credentials:1214.v1de940103927
    - git:5.0.0
    - git-client:4.1.0    
    - kubernetes:3883.v4d70a_a_a_df034
    - pipeline-utility-steps:2.15.1
    - pipeline-model-definition:2.2118.v31fd5b_9944b_5
    - slack:631.v40deea_40323b
    - thinBackup:1.15
    - workflow-aggregator:590.v6a_d052e5a_a_b_5
    - ssh-slaves:2.854.v7fd446b_337c9
    - ssh-agent:295.v9ca_a_1c7cc3a_a_
    - jdk-tool:63.v62d2fd4b_4793
    - command-launcher:90.v669d7ccb_7c31
    - github-oauth:0.39        
    ingress:
      enabled: true
     
  
    # DockerAMI: 
    # GProject:
    # GAuthFile:
    # GlobalLibraries: true
  rbac:
    create: true
